// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct __pthread_internal_slist __pthread_slist_t;
 * }
 */
public final class __pthread_slist_t extends __pthread_internal_slist {

    // Suppresses default constructor, ensuring non-instantiability.
    private __pthread_slist_t() {}
}


