// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$922 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GFileOutputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GFileOutputStream$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GFileOutputStream",
        constants$922.glib_queueautoptr_cleanup_GFileOutputStream$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GFilterInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GFilterInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GFilterInputStream",
        constants$922.glib_autoptr_clear_GFilterInputStream$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GFilterInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GFilterInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GFilterInputStream",
        constants$922.glib_autoptr_cleanup_GFilterInputStream$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GFilterInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GFilterInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GFilterInputStream",
        constants$922.glib_listautoptr_cleanup_GFilterInputStream$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GFilterInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GFilterInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GFilterInputStream",
        constants$922.glib_slistautoptr_cleanup_GFilterInputStream$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GFilterInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GFilterInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GFilterInputStream",
        constants$922.glib_queueautoptr_cleanup_GFilterInputStream$FUNC
    );
}


