// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$160 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$160() {}
    static final FunctionDescriptor g_hook_list_marshal$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hook_list_marshal$MH = RuntimeHelper.downcallHandle(
        "g_hook_list_marshal",
        constants$160.g_hook_list_marshal$FUNC
    );
    static final FunctionDescriptor g_hook_list_marshal_check$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hook_list_marshal_check$MH = RuntimeHelper.downcallHandle(
        "g_hook_list_marshal_check",
        constants$160.g_hook_list_marshal_check$FUNC
    );
    static final FunctionDescriptor g_hostname_is_non_ascii$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hostname_is_non_ascii$MH = RuntimeHelper.downcallHandle(
        "g_hostname_is_non_ascii",
        constants$160.g_hostname_is_non_ascii$FUNC
    );
    static final FunctionDescriptor g_hostname_is_ascii_encoded$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hostname_is_ascii_encoded$MH = RuntimeHelper.downcallHandle(
        "g_hostname_is_ascii_encoded",
        constants$160.g_hostname_is_ascii_encoded$FUNC
    );
    static final FunctionDescriptor g_hostname_is_ip_address$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hostname_is_ip_address$MH = RuntimeHelper.downcallHandle(
        "g_hostname_is_ip_address",
        constants$160.g_hostname_is_ip_address$FUNC
    );
    static final FunctionDescriptor g_hostname_to_ascii$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hostname_to_ascii$MH = RuntimeHelper.downcallHandle(
        "g_hostname_to_ascii",
        constants$160.g_hostname_to_ascii$FUNC
    );
}


