// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1940 {

    static final FunctionDescriptor gtk_print_settings_get_paper_width$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_paper_width$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_paper_width",
        constants$1940.gtk_print_settings_get_paper_width$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_set_paper_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_paper_width$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_paper_width",
        constants$1940.gtk_print_settings_set_paper_width$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_get_paper_height$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_paper_height$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_paper_height",
        constants$1940.gtk_print_settings_get_paper_height$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_set_paper_height$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_paper_height$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_paper_height",
        constants$1940.gtk_print_settings_set_paper_height$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_get_use_color$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_use_color$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_use_color",
        constants$1940.gtk_print_settings_get_use_color$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_set_use_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_use_color$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_use_color",
        constants$1940.gtk_print_settings_set_use_color$FUNC
    );
}


