// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1447 {

    static final FunctionDescriptor gtk_widget_get_screen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_screen$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_screen",
        constants$1447.gtk_widget_get_screen$FUNC
    );
    static final FunctionDescriptor gtk_widget_has_screen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_has_screen$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_has_screen",
        constants$1447.gtk_widget_has_screen$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_scale_factor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_scale_factor$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_scale_factor",
        constants$1447.gtk_widget_get_scale_factor$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_display$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_display",
        constants$1447.gtk_widget_get_display$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_root_window$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_root_window$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_root_window",
        constants$1447.gtk_widget_get_root_window$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_settings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_settings",
        constants$1447.gtk_widget_get_settings$FUNC
    );
}


