// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$845 {

    static final FunctionDescriptor g_subprocess_launcher_take_stderr_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_take_stderr_fd$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_take_stderr_fd",
        constants$845.g_subprocess_launcher_take_stderr_fd$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_take_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_take_fd$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_take_fd",
        constants$845.g_subprocess_launcher_take_fd$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_close$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_close",
        constants$845.g_subprocess_launcher_close$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_set_child_setup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_set_child_setup$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_set_child_setup",
        constants$845.g_subprocess_launcher_set_child_setup$FUNC
    );
    static final FunctionDescriptor g_task_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_task_get_type$MH = RuntimeHelper.downcallHandle(
        "g_task_get_type",
        constants$845.g_task_get_type$FUNC
    );
    static final FunctionDescriptor g_task_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_task_new$MH = RuntimeHelper.downcallHandle(
        "g_task_new",
        constants$845.g_task_new$FUNC
    );
}


