// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1440 {

    static final FunctionDescriptor gtk_widget_get_mapped$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_mapped$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_mapped",
        constants$1440.gtk_widget_get_mapped$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_app_paintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_app_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_app_paintable",
        constants$1440.gtk_widget_set_app_paintable$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_app_paintable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_app_paintable$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_app_paintable",
        constants$1440.gtk_widget_get_app_paintable$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_double_buffered$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_double_buffered$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_double_buffered",
        constants$1440.gtk_widget_set_double_buffered$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_double_buffered$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_double_buffered$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_double_buffered",
        constants$1440.gtk_widget_get_double_buffered$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_redraw_on_allocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_redraw_on_allocate$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_redraw_on_allocate",
        constants$1440.gtk_widget_set_redraw_on_allocate$FUNC
    );
}


