// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1054 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1054() {}
    static final FunctionDescriptor cairo_region_xor_rectangle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_region_xor_rectangle$MH = RuntimeHelper.downcallHandle(
        "cairo_region_xor_rectangle",
        constants$1054.cairo_region_xor_rectangle$FUNC
    );
    static final FunctionDescriptor cairo_debug_reset_static_data$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle cairo_debug_reset_static_data$MH = RuntimeHelper.downcallHandle(
        "cairo_debug_reset_static_data",
        constants$1054.cairo_debug_reset_static_data$FUNC
    );
    static final FunctionDescriptor gdk_device_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_device_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_type",
        constants$1054.gdk_device_get_type$FUNC
    );
    static final FunctionDescriptor gdk_device_get_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_name$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_name",
        constants$1054.gdk_device_get_name$FUNC
    );
    static final FunctionDescriptor gdk_device_get_has_cursor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_has_cursor$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_has_cursor",
        constants$1054.gdk_device_get_has_cursor$FUNC
    );
    static final FunctionDescriptor gdk_device_get_source$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_get_source$MH = RuntimeHelper.downcallHandle(
        "gdk_device_get_source",
        constants$1054.gdk_device_get_source$FUNC
    );
}


