// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1663 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1663() {}
    static final FunctionDescriptor gtk_im_multicontext_set_context_id$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_im_multicontext_set_context_id$MH = RuntimeHelper.downcallHandle(
        "gtk_im_multicontext_set_context_id",
        constants$1663.gtk_im_multicontext_set_context_id$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_info_bar_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_get_type",
        constants$1663.gtk_info_bar_get_type$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_info_bar_new$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_new",
        constants$1663.gtk_info_bar_new$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_new_with_buttons$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_new_with_buttons$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_info_bar_new_with_buttons",
        constants$1663.gtk_info_bar_new_with_buttons$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_get_action_area$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_get_action_area$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_get_action_area",
        constants$1663.gtk_info_bar_get_action_area$FUNC
    );
    static final FunctionDescriptor gtk_info_bar_get_content_area$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_get_content_area$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_get_content_area",
        constants$1663.gtk_info_bar_get_content_area$FUNC
    );
}


