// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$712 {

    static final FunctionDescriptor g_inet_address_get_is_multicast$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_multicast$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_multicast",
        constants$712.g_inet_address_get_is_multicast$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_global$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_global$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_global",
        constants$712.g_inet_address_get_is_mc_global$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_link_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_link_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_link_local",
        constants$712.g_inet_address_get_is_mc_link_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_node_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_node_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_node_local",
        constants$712.g_inet_address_get_is_mc_node_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_org_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_org_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_org_local",
        constants$712.g_inet_address_get_is_mc_org_local$FUNC
    );
    static final FunctionDescriptor g_inet_address_get_is_mc_site_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_inet_address_get_is_mc_site_local$MH = RuntimeHelper.downcallHandle(
        "g_inet_address_get_is_mc_site_local",
        constants$712.g_inet_address_get_is_mc_site_local$FUNC
    );
}


