// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$685 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$685() {}
    static final FunctionDescriptor g_io_modules_scan_all_in_directory_with_scope$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_modules_scan_all_in_directory_with_scope$MH = RuntimeHelper.downcallHandle(
        "g_io_modules_scan_all_in_directory_with_scope",
        constants$685.g_io_modules_scan_all_in_directory_with_scope$FUNC
    );
    static final FunctionDescriptor g_io_modules_load_all_in_directory_with_scope$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_modules_load_all_in_directory_with_scope$MH = RuntimeHelper.downcallHandle(
        "g_io_modules_load_all_in_directory_with_scope",
        constants$685.g_io_modules_load_all_in_directory_with_scope$FUNC
    );
    static final FunctionDescriptor g_io_extension_point_register$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_extension_point_register$MH = RuntimeHelper.downcallHandle(
        "g_io_extension_point_register",
        constants$685.g_io_extension_point_register$FUNC
    );
    static final FunctionDescriptor g_io_extension_point_lookup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_extension_point_lookup$MH = RuntimeHelper.downcallHandle(
        "g_io_extension_point_lookup",
        constants$685.g_io_extension_point_lookup$FUNC
    );
    static final FunctionDescriptor g_io_extension_point_set_required_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_io_extension_point_set_required_type$MH = RuntimeHelper.downcallHandle(
        "g_io_extension_point_set_required_type",
        constants$685.g_io_extension_point_set_required_type$FUNC
    );
    static final FunctionDescriptor g_io_extension_point_get_required_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_extension_point_get_required_type$MH = RuntimeHelper.downcallHandle(
        "g_io_extension_point_get_required_type",
        constants$685.g_io_extension_point_get_required_type$FUNC
    );
}


