// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2015 {

    static final FunctionDescriptor gtk_spin_button_get_update_policy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_spin_button_get_update_policy$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_get_update_policy",
        constants$2015.gtk_spin_button_get_update_policy$FUNC
    );
    static final FunctionDescriptor gtk_spin_button_set_numeric$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_spin_button_set_numeric$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_set_numeric",
        constants$2015.gtk_spin_button_set_numeric$FUNC
    );
    static final FunctionDescriptor gtk_spin_button_get_numeric$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_spin_button_get_numeric$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_get_numeric",
        constants$2015.gtk_spin_button_get_numeric$FUNC
    );
    static final FunctionDescriptor gtk_spin_button_spin$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_spin_button_spin$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_spin",
        constants$2015.gtk_spin_button_spin$FUNC
    );
    static final FunctionDescriptor gtk_spin_button_set_wrap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_spin_button_set_wrap$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_set_wrap",
        constants$2015.gtk_spin_button_set_wrap$FUNC
    );
    static final FunctionDescriptor gtk_spin_button_get_wrap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_spin_button_get_wrap$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_get_wrap",
        constants$2015.gtk_spin_button_get_wrap$FUNC
    );
}


