// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$542 {

    static final FunctionDescriptor g_initable_newv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_initable_newv$MH = RuntimeHelper.downcallHandle(
        "g_initable_newv",
        constants$542.g_initable_newv$FUNC
    );
    static final FunctionDescriptor g_initable_new_valist$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_initable_new_valist$MH = RuntimeHelper.downcallHandle(
        "g_initable_new_valist",
        constants$542.g_initable_new_valist$FUNC
    );
    static final FunctionDescriptor g_async_initable_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_async_initable_get_type$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_get_type",
        constants$542.g_async_initable_get_type$FUNC
    );
    static final FunctionDescriptor g_async_initable_init_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_init_async$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_init_async",
        constants$542.g_async_initable_init_async$FUNC
    );
    static final FunctionDescriptor g_async_initable_init_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_init_finish$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_init_finish",
        constants$542.g_async_initable_init_finish$FUNC
    );
    static final FunctionDescriptor g_async_initable_new_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_new_async$MH = RuntimeHelper.downcallHandleVariadic(
        "g_async_initable_new_async",
        constants$542.g_async_initable_new_async$FUNC
    );
}


