// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$822 {

    static final FunctionDescriptor g_socket_send_message$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_send_message$MH = RuntimeHelper.downcallHandle(
        "g_socket_send_message",
        constants$822.g_socket_send_message$FUNC
    );
    static final FunctionDescriptor g_socket_receive_messages$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_receive_messages$MH = RuntimeHelper.downcallHandle(
        "g_socket_receive_messages",
        constants$822.g_socket_receive_messages$FUNC
    );
    static final FunctionDescriptor g_socket_send_messages$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_send_messages$MH = RuntimeHelper.downcallHandle(
        "g_socket_send_messages",
        constants$822.g_socket_send_messages$FUNC
    );
    static final FunctionDescriptor g_socket_close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_close$MH = RuntimeHelper.downcallHandle(
        "g_socket_close",
        constants$822.g_socket_close$FUNC
    );
    static final FunctionDescriptor g_socket_shutdown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_shutdown$MH = RuntimeHelper.downcallHandle(
        "g_socket_shutdown",
        constants$822.g_socket_shutdown$FUNC
    );
    static final FunctionDescriptor g_socket_is_closed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_is_closed$MH = RuntimeHelper.downcallHandle(
        "g_socket_is_closed",
        constants$822.g_socket_is_closed$FUNC
    );
}


