// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2172 {

    static final FunctionDescriptor gtk_ui_manager_insert_action_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_insert_action_group$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_insert_action_group",
        constants$2172.gtk_ui_manager_insert_action_group$FUNC
    );
    static final FunctionDescriptor gtk_ui_manager_remove_action_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_remove_action_group$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_remove_action_group",
        constants$2172.gtk_ui_manager_remove_action_group$FUNC
    );
    static final FunctionDescriptor gtk_ui_manager_get_action_groups$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_get_action_groups$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_get_action_groups",
        constants$2172.gtk_ui_manager_get_action_groups$FUNC
    );
    static final FunctionDescriptor gtk_ui_manager_get_accel_group$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_get_accel_group$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_get_accel_group",
        constants$2172.gtk_ui_manager_get_accel_group$FUNC
    );
    static final FunctionDescriptor gtk_ui_manager_get_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_get_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_get_widget",
        constants$2172.gtk_ui_manager_get_widget$FUNC
    );
    static final FunctionDescriptor gtk_ui_manager_get_toplevels$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_ui_manager_get_toplevels$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_get_toplevels",
        constants$2172.gtk_ui_manager_get_toplevels$FUNC
    );
}


