// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1842 {

    static final FunctionDescriptor gtk_icon_info_load_icon_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_icon_async$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_icon_async",
        constants$1842.gtk_icon_info_load_icon_async$FUNC
    );
    static final FunctionDescriptor gtk_icon_info_load_icon_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_icon_finish$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_icon_finish",
        constants$1842.gtk_icon_info_load_icon_finish$FUNC
    );
    static final FunctionDescriptor gtk_icon_info_load_symbolic$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_symbolic$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_symbolic",
        constants$1842.gtk_icon_info_load_symbolic$FUNC
    );
    static final FunctionDescriptor gtk_icon_info_load_symbolic_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_symbolic_async$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_symbolic_async",
        constants$1842.gtk_icon_info_load_symbolic_async$FUNC
    );
    static final FunctionDescriptor gtk_icon_info_load_symbolic_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_symbolic_finish$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_symbolic_finish",
        constants$1842.gtk_icon_info_load_symbolic_finish$FUNC
    );
    static final FunctionDescriptor gtk_icon_info_load_symbolic_for_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_info_load_symbolic_for_context$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_info_load_symbolic_for_context",
        constants$1842.gtk_icon_info_load_symbolic_for_context$FUNC
    );
}


