// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1133() {}
    static final FunctionDescriptor gdk_pixbuf_new_from_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_new_from_bytes$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_new_from_bytes",
        constants$1133.gdk_pixbuf_new_from_bytes$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_new_from_xpm_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_new_from_xpm_data$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_new_from_xpm_data",
        constants$1133.gdk_pixbuf_new_from_xpm_data$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_new_from_inline$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_new_from_inline$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_new_from_inline",
        constants$1133.gdk_pixbuf_new_from_inline$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_fill$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_fill$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_fill",
        constants$1133.gdk_pixbuf_fill$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_save$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_save$MH = RuntimeHelper.downcallHandleVariadic(
        "gdk_pixbuf_save",
        constants$1133.gdk_pixbuf_save$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_savev$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_savev$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_savev",
        constants$1133.gdk_pixbuf_savev$FUNC
    );
}


