// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1791 {

    static final FunctionDescriptor GtkFontFilterFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkFontFilterFunc$MH = RuntimeHelper.downcallHandle(
        constants$1791.GtkFontFilterFunc$FUNC
    );
    static final FunctionDescriptor gtk_font_chooser_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_font_chooser_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_font_chooser_get_type",
        constants$1791.gtk_font_chooser_get_type$FUNC
    );
    static final FunctionDescriptor gtk_font_chooser_get_font_family$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_chooser_get_font_family$MH = RuntimeHelper.downcallHandle(
        "gtk_font_chooser_get_font_family",
        constants$1791.gtk_font_chooser_get_font_family$FUNC
    );
    static final FunctionDescriptor gtk_font_chooser_get_font_face$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_chooser_get_font_face$MH = RuntimeHelper.downcallHandle(
        "gtk_font_chooser_get_font_face",
        constants$1791.gtk_font_chooser_get_font_face$FUNC
    );
    static final FunctionDescriptor gtk_font_chooser_get_font_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_chooser_get_font_size$MH = RuntimeHelper.downcallHandle(
        "gtk_font_chooser_get_font_size",
        constants$1791.gtk_font_chooser_get_font_size$FUNC
    );
    static final FunctionDescriptor gtk_font_chooser_get_font_desc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_chooser_get_font_desc$MH = RuntimeHelper.downcallHandle(
        "gtk_font_chooser_get_font_desc",
        constants$1791.gtk_font_chooser_get_font_desc$FUNC
    );
}


