// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface GHookCompareFunc {

    int apply(java.lang.foreign.MemoryAddress new_hook, java.lang.foreign.MemoryAddress sibling);
    static MemorySegment allocate(GHookCompareFunc fi, MemorySession session) {
        return RuntimeHelper.upcallStub(GHookCompareFunc.class, fi, constants$152.GHookCompareFunc$FUNC, session);
    }
    static GHookCompareFunc ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _new_hook, java.lang.foreign.MemoryAddress _sibling) -> {
            try {
                return (int)constants$152.GHookCompareFunc$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_new_hook, (java.lang.foreign.Addressable)_sibling);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


