// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface GSettingsBindSetMapping {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress value, java.lang.foreign.MemoryAddress expected_type, java.lang.foreign.MemoryAddress user_data);
    static MemorySegment allocate(GSettingsBindSetMapping fi, MemorySession session) {
        return RuntimeHelper.upcallStub(GSettingsBindSetMapping.class, fi, constants$804.GSettingsBindSetMapping$FUNC, session);
    }
    static GSettingsBindSetMapping ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _value, java.lang.foreign.MemoryAddress _expected_type, java.lang.foreign.MemoryAddress _user_data) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$805.GSettingsBindSetMapping$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_value, (java.lang.foreign.Addressable)_expected_type, (java.lang.foreign.Addressable)_user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


