// Generated by jextract

package org.purejava.linux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _GtkColorChooserWidget GtkColorChooserWidget;
 * }
 */
public final class GtkColorChooserWidget extends _GtkColorChooserWidget {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkColorChooserWidget() {}
}


