// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

/**
 * {@snippet :
 * struct _PangoColor {
 *     guint16 red;
 *     guint16 green;
 *     guint16 blue;
 * };
 * }
 */
public class _PangoColor {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("red"),
        Constants$root.C_SHORT$LAYOUT.withName("green"),
        Constants$root.C_SHORT$LAYOUT.withName("blue")
    ).withName("_PangoColor");
    public static MemoryLayout $LAYOUT() {
        return _PangoColor.$struct$LAYOUT;
    }
    static final VarHandle red$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("red"));
    public static VarHandle red$VH() {
        return _PangoColor.red$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * guint16 red;
     * }
     */
    public static short red$get(MemorySegment seg) {
        return (short)_PangoColor.red$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * guint16 red;
     * }
     */
    public static void red$set(MemorySegment seg, short x) {
        _PangoColor.red$VH.set(seg, x);
    }
    public static short red$get(MemorySegment seg, long index) {
        return (short)_PangoColor.red$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void red$set(MemorySegment seg, long index, short x) {
        _PangoColor.red$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle green$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("green"));
    public static VarHandle green$VH() {
        return _PangoColor.green$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * guint16 green;
     * }
     */
    public static short green$get(MemorySegment seg) {
        return (short)_PangoColor.green$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * guint16 green;
     * }
     */
    public static void green$set(MemorySegment seg, short x) {
        _PangoColor.green$VH.set(seg, x);
    }
    public static short green$get(MemorySegment seg, long index) {
        return (short)_PangoColor.green$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void green$set(MemorySegment seg, long index, short x) {
        _PangoColor.green$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle blue$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("blue"));
    public static VarHandle blue$VH() {
        return _PangoColor.blue$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * guint16 blue;
     * }
     */
    public static short blue$get(MemorySegment seg) {
        return (short)_PangoColor.blue$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * guint16 blue;
     * }
     */
    public static void blue$set(MemorySegment seg, short x) {
        _PangoColor.blue$VH.set(seg, x);
    }
    public static short blue$get(MemorySegment seg, long index) {
        return (short)_PangoColor.blue$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void blue$set(MemorySegment seg, long index, short x) {
        _PangoColor.blue$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


