// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$3337 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3337() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_GtkStatusIconClass.__gtk_reserved3.class, "apply", constants$7.const$5);
    static final VarHandle const$1 = constants$3333.const$5.varHandle(MemoryLayout.PathElement.groupElement("__gtk_reserved3"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_GtkStatusIconClass.__gtk_reserved4.class, "apply", constants$7.const$5);
    static final VarHandle const$3 = constants$3333.const$5.varHandle(MemoryLayout.PathElement.groupElement("__gtk_reserved4"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gtk_status_icon_get_type",
        constants$3.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_status_icon_new",
        constants$35.const$2
    );
}


