// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$2054 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2054() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_AtkRelationSetClass.pad2.class, "apply", constants$10.const$5);
    static final VarHandle const$1 = constants$2053.const$3.varHandle(MemoryLayout.PathElement.groupElement("pad2"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "atk_relation_set_get_type",
        constants$3.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "atk_relation_set_new",
        constants$35.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "atk_relation_set_contains",
        constants$11.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "atk_relation_set_contains_target",
        constants$150.const$0
    );
}


