// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_SHORT;
final class constants$1320 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1320() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "g_socket_service_stop",
        constants$13.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "g_socket_service_is_active",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "g_srv_target_get_type",
        constants$3.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "g_srv_target_new",
        constants$1320.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "g_srv_target_copy",
        constants$5.const$2
    );
}


