// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$355 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$355() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "g_variant_get_boolean",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "g_variant_get_byte",
        constants$186.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "g_variant_get_int16",
        constants$186.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "g_variant_get_uint16",
        constants$186.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "g_variant_get_int32",
        constants$10.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "g_variant_get_uint32",
        constants$10.const$5
    );
}


