// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2545 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2545() {}
    static final VarHandle const$0 = constants$2543.const$4.varHandle(MemoryLayout.PathElement.groupElement("set_buildable_property"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(_GtkBuildableIface.construct_child.class, "apply", constants$23.const$0);
    static final VarHandle const$2 = constants$2543.const$4.varHandle(MemoryLayout.PathElement.groupElement("construct_child"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(_GtkBuildableIface.custom_tag_start.class, "apply", constants$638.const$1);
    static final VarHandle const$4 = constants$2543.const$4.varHandle(MemoryLayout.PathElement.groupElement("custom_tag_start"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(_GtkBuildableIface.custom_tag_end.class, "apply", constants$331.const$1);
}


