// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$590 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$590() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(g_cclosure_new$destroy_data.class, "apply", constants$13.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "g_cclosure_new",
        constants$23.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(g_cclosure_new_swap$callback_func.class, "apply", constants$7.const$5);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(g_cclosure_new_swap$destroy_data.class, "apply", constants$13.const$4);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "g_cclosure_new_swap",
        constants$23.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "g_signal_type_cclosure_new",
        constants$63.const$1
    );
}


