// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$599 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$599() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "g_cclosure_marshal_STRING__OBJECT_POINTER",
        constants$584.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "g_cclosure_marshal_STRING__OBJECT_POINTERv",
        constants$585.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "g_cclosure_marshal_BOOLEAN__BOXED_BOXED",
        constants$584.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv",
        constants$585.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(GSignalCMarshaller.class, "apply", constants$584.const$3);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(GSignalCVaMarshaller.class, "apply", constants$585.const$0);
}


