// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$790 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$790() {}
    static final FunctionDescriptor g_subprocess_launcher_set_stdout_file_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_set_stdout_file_path$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_set_stdout_file_path",
        constants$790.g_subprocess_launcher_set_stdout_file_path$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_take_stdout_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_take_stdout_fd$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_take_stdout_fd",
        constants$790.g_subprocess_launcher_take_stdout_fd$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_set_stderr_file_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_set_stderr_file_path$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_set_stderr_file_path",
        constants$790.g_subprocess_launcher_set_stderr_file_path$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_take_stderr_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_take_stderr_fd$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_take_stderr_fd",
        constants$790.g_subprocess_launcher_take_stderr_fd$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_take_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_take_fd$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_take_fd",
        constants$790.g_subprocess_launcher_take_fd$FUNC
    );
    static final FunctionDescriptor g_subprocess_launcher_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_subprocess_launcher_close$MH = RuntimeHelper.downcallHandle(
        "g_subprocess_launcher_close",
        constants$790.g_subprocess_launcher_close$FUNC
    );
}


