// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1029 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1029() {}
    static final FunctionDescriptor cairo_surface_observer_add_mask_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_mask_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_mask_callback",
        constants$1029.cairo_surface_observer_add_mask_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_fill_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_fill_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_fill_callback",
        constants$1029.cairo_surface_observer_add_fill_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_stroke_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_stroke_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_stroke_callback",
        constants$1029.cairo_surface_observer_add_stroke_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_glyphs_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_glyphs_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_glyphs_callback",
        constants$1029.cairo_surface_observer_add_glyphs_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_flush_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_flush_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_flush_callback",
        constants$1029.cairo_surface_observer_add_flush_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_finish_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_finish_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_finish_callback",
        constants$1029.cairo_surface_observer_add_finish_callback$FUNC
    );
}


