// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$438 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$438() {}
    static final FunctionDescriptor g_object_add_toggle_ref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_add_toggle_ref$MH = RuntimeHelper.downcallHandle(
        "g_object_add_toggle_ref",
        constants$438.g_object_add_toggle_ref$FUNC
    );
    static final FunctionDescriptor g_object_remove_toggle_ref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_remove_toggle_ref$MH = RuntimeHelper.downcallHandle(
        "g_object_remove_toggle_ref",
        constants$438.g_object_remove_toggle_ref$FUNC
    );
    static final FunctionDescriptor g_object_get_qdata$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_object_get_qdata$MH = RuntimeHelper.downcallHandle(
        "g_object_get_qdata",
        constants$438.g_object_get_qdata$FUNC
    );
    static final FunctionDescriptor g_object_set_qdata$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_set_qdata$MH = RuntimeHelper.downcallHandle(
        "g_object_set_qdata",
        constants$438.g_object_set_qdata$FUNC
    );
    static final FunctionDescriptor g_object_set_qdata_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_set_qdata_full$MH = RuntimeHelper.downcallHandle(
        "g_object_set_qdata_full",
        constants$438.g_object_set_qdata_full$FUNC
    );
    static final FunctionDescriptor g_object_steal_qdata$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_object_steal_qdata$MH = RuntimeHelper.downcallHandle(
        "g_object_steal_qdata",
        constants$438.g_object_steal_qdata$FUNC
    );
}


