// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1874 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1874() {}
    static final FunctionDescriptor gtk_tree_store_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_tree_store_set",
        constants$1874.gtk_tree_store_set$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_set_valuesv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set_valuesv$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_set_valuesv",
        constants$1874.gtk_tree_store_set_valuesv$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_set_valist$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set_valist$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_set_valist",
        constants$1874.gtk_tree_store_set_valist$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_remove$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_remove",
        constants$1874.gtk_tree_store_remove$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_insert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert",
        constants$1874.gtk_tree_store_insert$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_insert_before$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert_before$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert_before",
        constants$1874.gtk_tree_store_insert_before$FUNC
    );
}


