// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$738 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$738() {}
    static final FunctionDescriptor g_seekable_can_truncate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_seekable_can_truncate$MH = RuntimeHelper.downcallHandle(
        "g_seekable_can_truncate",
        constants$738.g_seekable_can_truncate$FUNC
    );
    static final FunctionDescriptor g_seekable_truncate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_seekable_truncate$MH = RuntimeHelper.downcallHandle(
        "g_seekable_truncate",
        constants$738.g_seekable_truncate$FUNC
    );
    static final FunctionDescriptor g_settings_schema_source_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_settings_schema_source_get_type$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_source_get_type",
        constants$738.g_settings_schema_source_get_type$FUNC
    );
    static final FunctionDescriptor g_settings_schema_source_get_default$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_settings_schema_source_get_default$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_source_get_default",
        constants$738.g_settings_schema_source_get_default$FUNC
    );
    static final FunctionDescriptor g_settings_schema_source_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_source_ref$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_source_ref",
        constants$738.g_settings_schema_source_ref$FUNC
    );
    static final FunctionDescriptor g_settings_schema_source_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_source_unref$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_source_unref",
        constants$738.g_settings_schema_source_unref$FUNC
    );
}


