// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$728 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$728() {}
    static final FunctionDescriptor g_proxy_address_get_password$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_password$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_password",
        constants$728.g_proxy_address_get_password$FUNC
    );
    static final FunctionDescriptor g_proxy_address_get_uri$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_uri$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_uri",
        constants$728.g_proxy_address_get_uri$FUNC
    );
    static final FunctionDescriptor g_socket_address_enumerator_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_socket_address_enumerator_get_type$MH = RuntimeHelper.downcallHandle(
        "g_socket_address_enumerator_get_type",
        constants$728.g_socket_address_enumerator_get_type$FUNC
    );
    static final FunctionDescriptor g_socket_address_enumerator_next$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_address_enumerator_next$MH = RuntimeHelper.downcallHandle(
        "g_socket_address_enumerator_next",
        constants$728.g_socket_address_enumerator_next$FUNC
    );
    static final FunctionDescriptor g_socket_address_enumerator_next_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_address_enumerator_next_async$MH = RuntimeHelper.downcallHandle(
        "g_socket_address_enumerator_next_async",
        constants$728.g_socket_address_enumerator_next_async$FUNC
    );
    static final FunctionDescriptor g_socket_address_enumerator_next_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_address_enumerator_next_finish$MH = RuntimeHelper.downcallHandle(
        "g_socket_address_enumerator_next_finish",
        constants$728.g_socket_address_enumerator_next_finish$FUNC
    );
}


