// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$2075 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2075() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_AtkTableIface.get_row_extent_at.class, "apply", constants$49.const$0);
    static final VarHandle const$1 = constants$2072.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_row_extent_at"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_AtkTableIface.get_caption.class, "apply", constants$5.const$2);
    static final VarHandle const$3 = constants$2072.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_caption"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(_AtkTableIface.get_column_description.class, "apply", constants$21.const$3);
    static final VarHandle const$5 = constants$2072.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_column_description"));
}


