// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$1618 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1618() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_copy",
        constants$5.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_free",
        constants$13.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_init_start",
        constants$12.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_init_end",
        constants$12.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_next_cluster",
        constants$10.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "pango_glyph_item_iter_prev_cluster",
        constants$10.const$5
    );
}


