// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1580 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1580() {}
    static final FunctionDescriptor gtk_file_chooser_set_choice$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_file_chooser_set_choice$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_set_choice",
        constants$1580.gtk_file_chooser_set_choice$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_get_choice$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_file_chooser_get_choice$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_get_choice",
        constants$1580.gtk_file_chooser_get_choice$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_button_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_file_chooser_button_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_button_get_type",
        constants$1580.gtk_file_chooser_button_get_type$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_button_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_file_chooser_button_new$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_button_new",
        constants$1580.gtk_file_chooser_button_new$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_button_new_with_dialog$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_file_chooser_button_new_with_dialog$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_button_new_with_dialog",
        constants$1580.gtk_file_chooser_button_new_with_dialog$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_button_get_title$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_file_chooser_button_get_title$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_button_get_title",
        constants$1580.gtk_file_chooser_button_get_title$FUNC
    );
}


