// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1617 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1617() {}
    static final FunctionDescriptor gtk_header_bar_set_subtitle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_set_subtitle$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_set_subtitle",
        constants$1617.gtk_header_bar_set_subtitle$FUNC
    );
    static final FunctionDescriptor gtk_header_bar_get_subtitle$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_get_subtitle$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_get_subtitle",
        constants$1617.gtk_header_bar_get_subtitle$FUNC
    );
    static final FunctionDescriptor gtk_header_bar_set_custom_title$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_set_custom_title$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_set_custom_title",
        constants$1617.gtk_header_bar_set_custom_title$FUNC
    );
    static final FunctionDescriptor gtk_header_bar_get_custom_title$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_get_custom_title$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_get_custom_title",
        constants$1617.gtk_header_bar_get_custom_title$FUNC
    );
    static final FunctionDescriptor gtk_header_bar_pack_start$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_pack_start$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_pack_start",
        constants$1617.gtk_header_bar_pack_start$FUNC
    );
    static final FunctionDescriptor gtk_header_bar_pack_end$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_pack_end$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_pack_end",
        constants$1617.gtk_header_bar_pack_end$FUNC
    );
}


