// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1105 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1105() {}
    static final FunctionDescriptor gdk_window_get_frame_clock$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_get_frame_clock$MH = RuntimeHelper.downcallHandle(
        "gdk_window_get_frame_clock",
        constants$1105.gdk_window_get_frame_clock$FUNC
    );
    static final FunctionDescriptor gdk_window_set_opaque_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_opaque_region$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_opaque_region",
        constants$1105.gdk_window_set_opaque_region$FUNC
    );
    static final FunctionDescriptor gdk_window_set_event_compression$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_set_event_compression$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_event_compression",
        constants$1105.gdk_window_set_event_compression$FUNC
    );
    static final FunctionDescriptor gdk_window_get_event_compression$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_get_event_compression$MH = RuntimeHelper.downcallHandle(
        "gdk_window_get_event_compression",
        constants$1105.gdk_window_get_event_compression$FUNC
    );
    static final FunctionDescriptor gdk_window_set_shadow_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_set_shadow_width$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_shadow_width",
        constants$1105.gdk_window_set_shadow_width$FUNC
    );
    static final FunctionDescriptor gdk_window_show_window_menu$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_show_window_menu$MH = RuntimeHelper.downcallHandle(
        "gdk_window_show_window_menu",
        constants$1105.gdk_window_show_window_menu$FUNC
    );
}


