// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3109 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3109() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_GtkStatusbarClass.text_pushed.class, "apply", constants$42.const$4);
    static final VarHandle const$1 = constants$3108.const$4.varHandle(MemoryLayout.PathElement.groupElement("text_pushed"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_GtkStatusbarClass.text_popped.class, "apply", constants$42.const$4);
    static final VarHandle const$3 = constants$3108.const$4.varHandle(MemoryLayout.PathElement.groupElement("text_popped"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(_GtkStatusbarClass._gtk_reserved1.class, "apply", constants$7.const$5);
    static final VarHandle const$5 = constants$3108.const$4.varHandle(MemoryLayout.PathElement.groupElement("_gtk_reserved1"));
}


