// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$1665 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1665() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fgetc",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getc",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$83.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$10.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getchar_unlocked",
        constants$83.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fgetc_unlocked",
        constants$10.const$5
    );
}


