// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$2400 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2400() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gtk_drag_begin",
        constants$468.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gtk_drag_cancel",
        constants$13.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gtk_drag_set_icon_widget",
        constants$1046.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gtk_drag_set_icon_pixbuf",
        constants$1046.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gtk_drag_set_icon_stock",
        constants$1046.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_drag_set_icon_surface",
        constants$13.const$4
    );
}


