// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$1209 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1209() {}
    static final VarHandle const$0 = constants$1208.const$2.varHandle(MemoryLayout.PathElement.groupElement("acquire_async"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(_GPermissionClass.acquire_finish.class, "apply", constants$12.const$2);
    static final VarHandle const$2 = constants$1208.const$2.varHandle(MemoryLayout.PathElement.groupElement("acquire_finish"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(_GPermissionClass.release.class, "apply", constants$12.const$2);
    static final VarHandle const$4 = constants$1208.const$2.varHandle(MemoryLayout.PathElement.groupElement("release"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(_GPermissionClass.release_async.class, "apply", constants$42.const$1);
}


