// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$2184 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2184() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gtk_container_get_resize_mode",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gtk_container_check_resize",
        constants$13.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(gtk_container_foreach$callback.class, "apply", constants$13.const$4);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gtk_container_foreach",
        constants$14.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gtk_container_get_children",
        constants$5.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_container_propagate_draw",
        constants$14.const$3
    );
}


