// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$789 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$789() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_finish",
        constants$34.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(g_output_stream_writev_all_async$callback.class, "apply", constants$14.const$3);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_all_async",
        constants$761.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_all_finish",
        constants$34.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(g_output_stream_write_bytes_async$callback.class, "apply", constants$14.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "g_output_stream_write_bytes_async",
        constants$584.const$3
    );
}


