// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$836 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$836() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(_GDatagramBasedInterface.receive_messages.class, "apply", constants$836.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$836.const$0
    );
    static final VarHandle const$3 = constants$835.const$5.varHandle(MemoryLayout.PathElement.groupElement("receive_messages"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(_GDatagramBasedInterface.send_messages.class, "apply", constants$836.const$0);
    static final VarHandle const$5 = constants$835.const$5.varHandle(MemoryLayout.PathElement.groupElement("send_messages"));
}


