// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1400 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1400() {}
    static final FunctionDescriptor gtk_text_tag_event$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_tag_event$MH = RuntimeHelper.downcallHandle(
        "gtk_text_tag_event",
        constants$1400.gtk_text_tag_event$FUNC
    );
    static final FunctionDescriptor gtk_text_tag_changed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_tag_changed$MH = RuntimeHelper.downcallHandle(
        "gtk_text_tag_changed",
        constants$1400.gtk_text_tag_changed$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_get_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_get_buffer$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_get_buffer",
        constants$1400.gtk_text_iter_get_buffer$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_copy",
        constants$1400.gtk_text_iter_copy$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_free$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_free",
        constants$1400.gtk_text_iter_free$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_assign$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_assign$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_assign",
        constants$1400.gtk_text_iter_assign$FUNC
    );
}


