// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2301 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2301() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gtk_tree_iter_get_type",
        constants$3.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gtk_tree_model_get_type",
        constants$3.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gtk_tree_model_get_flags",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gtk_tree_model_get_n_columns",
        constants$10.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gtk_tree_model_get_column_type",
        constants$820.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_tree_model_get_iter",
        constants$12.const$2
    );
}


