// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_SHORT;
final class constants$1564 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1564() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "pango_font_get_languages",
        constants$5.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pango_font_serialize",
        constants$5.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "pango_font_deserialize",
        constants$23.const$0
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("red"),
        JAVA_SHORT.withName("green"),
        JAVA_SHORT.withName("blue")
    ).withName("_PangoColor");
    static final VarHandle const$4 = constants$1564.const$3.varHandle(MemoryLayout.PathElement.groupElement("red"));
    static final VarHandle const$5 = constants$1564.const$3.varHandle(MemoryLayout.PathElement.groupElement("green"));
}


