// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
final class constants$496 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$496() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(g_cache_new$key_equal_func.class, "apply", constants$9.const$0);
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "g_cache_new",
        constants$496.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "g_cache_destroy",
        constants$13.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "g_cache_insert",
        constants$5.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "g_cache_remove",
        constants$13.const$4
    );
}


