// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

final class constants$1837 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1837() {}
    static final FunctionDescriptor GtkTextBufferDeserializeFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor GtkTextBufferDeserializeFunc_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkTextBufferDeserializeFunc_UP$MH = RuntimeHelper.upcallHandle(GtkTextBufferDeserializeFunc.class, "apply", constants$1837.GtkTextBufferDeserializeFunc_UP$FUNC);
    static final FunctionDescriptor GtkTextBufferDeserializeFunc_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkTextBufferDeserializeFunc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$1837.GtkTextBufferDeserializeFunc_DOWN$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_register_serialize_format$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_register_serialize_format$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_register_serialize_format",
        constants$1837.gtk_text_buffer_register_serialize_format$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_register_serialize_tagset$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_register_serialize_tagset$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_register_serialize_tagset",
        constants$1837.gtk_text_buffer_register_serialize_tagset$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_register_deserialize_format$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_register_deserialize_format$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_register_deserialize_format",
        constants$1837.gtk_text_buffer_register_deserialize_format$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_register_deserialize_tagset$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_register_deserialize_tagset$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_register_deserialize_tagset",
        constants$1837.gtk_text_buffer_register_deserialize_tagset$FUNC
    );
}


