// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$2429 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2429() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gtk_list_store_prepend",
        constants$13.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gtk_list_store_append",
        constants$13.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gtk_list_store_clear",
        constants$13.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gtk_list_store_iter_is_valid",
        constants$9.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gtk_list_store_reorder",
        constants$13.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_list_store_swap",
        constants$14.const$3
    );
}


