// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$3281 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3281() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gtk_color_selection_is_adjusting",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gtk_color_selection_palette_from_string",
        constants$12.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gtk_color_selection_palette_to_string",
        constants$21.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(gtk_color_selection_set_change_palette_with_screen_hook$func.class, "apply", constants$164.const$5);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(gtk_color_selection_set_change_palette_with_screen_hook$return.class, "apply", constants$164.const$5);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gtk_color_selection_set_change_palette_with_screen_hook",
        constants$5.const$2
    );
}


