// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$2031 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2031() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_AtkEditableTextIface.copy_text.class, "apply", constants$469.const$2);
    static final VarHandle const$1 = constants$2029.const$5.varHandle(MemoryLayout.PathElement.groupElement("copy_text"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_AtkEditableTextIface.cut_text.class, "apply", constants$469.const$2);
    static final VarHandle const$3 = constants$2029.const$5.varHandle(MemoryLayout.PathElement.groupElement("cut_text"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(_AtkEditableTextIface.delete_text.class, "apply", constants$469.const$2);
    static final VarHandle const$5 = constants$2029.const$5.varHandle(MemoryLayout.PathElement.groupElement("delete_text"));
}


