// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
final class constants$1931 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1931() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gdk_keymap_get_scroll_lock_state",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "gdk_keymap_get_modifier_state",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gdk_keymap_add_virtual_modifiers",
        constants$13.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "gdk_keymap_map_virtual_modifiers",
        constants$9.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "gdk_keymap_get_modifier_mask",
        constants$11.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "gdk_keyval_name",
        constants$24.const$0
    );
}


