// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
final class constants$724 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$724() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(_GAppInfoIface.can_delete.class, "apply", constants$10.const$5);
    static final VarHandle const$1 = constants$718.const$1.varHandle(MemoryLayout.PathElement.groupElement("can_delete"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(_GAppInfoIface.do_delete.class, "apply", constants$10.const$5);
    static final VarHandle const$3 = constants$718.const$1.varHandle(MemoryLayout.PathElement.groupElement("do_delete"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(_GAppInfoIface.get_commandline.class, "apply", constants$5.const$2);
    static final VarHandle const$5 = constants$718.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_commandline"));
}


