// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GDataOutputStream GDataOutputStream
 * }
 */
public class GDataOutputStream extends _GDataOutputStream {

    GDataOutputStream() {
        // Should not be called directly
    }
}

