// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GQueue GQueue;
 * }
 */
public final class GQueue extends _GQueue {

    // Suppresses default constructor, ensuring non-instantiability.
    private GQueue() {}
}


