// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
/**
 * {@snippet :
 * void (*gtk_clipboard_request_targets$callback)(struct _GtkClipboard*,struct _GdkAtom**,int,void*);
 * }
 */
public interface gtk_clipboard_request_targets$callback {

    void apply(java.lang.foreign.MemorySegment clipboard, java.lang.foreign.MemorySegment atoms, int n_atoms, java.lang.foreign.MemorySegment data);
    static MemorySegment allocate(gtk_clipboard_request_targets$callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2629.const$5, fi, constants$464.const$4, scope);
    }
    static gtk_clipboard_request_targets$callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _clipboard, java.lang.foreign.MemorySegment _atoms, int _n_atoms, java.lang.foreign.MemorySegment _data) -> {
            try {
                constants$737.const$4.invokeExact(symbol, _clipboard, _atoms, _n_atoms, _data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


