// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkBinClass GtkBinClass
 * }
 */
public class GtkBinClass extends _GtkBinClass {

    GtkBinClass() {
        // Should not be called directly
    }
}

