// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GtkBindingArg GtkBindingArg;
 * }
 */
public final class GtkBindingArg extends _GtkBindingArg {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkBindingArg() {}
}


