// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GtkBorder GtkBorder;
 * }
 */
public final class GtkBorder extends _GtkBorder {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkBorder() {}
}


