// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _GtkBoxPrivate GtkBoxPrivate;
 * }
 */
public final class GtkBoxPrivate {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkBoxPrivate() {}
}


