// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GtkIconView GtkIconView;
 * }
 */
public final class GtkIconView extends _GtkIconView {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkIconView() {}
}


