// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkProgressBarClass GtkProgressBarClass
 * }
 */
public class GtkProgressBarClass extends _GtkProgressBarClass {

    GtkProgressBarClass() {
        // Should not be called directly
    }
}

