// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkScaleButton GtkScaleButton
 * }
 */
public class GtkScaleButton extends _GtkScaleButton {

    GtkScaleButton() {
        // Should not be called directly
    }
}

