// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GtkScrollableInterface GtkScrollableInterface;
 * }
 */
public final class GtkScrollableInterface extends _GtkScrollableInterface {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkScrollableInterface() {}
}


