// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
/**
 * {@snippet :
 * void (*GtkTreeSelectionForeachFunc)(struct _GtkTreeModel* model,struct _GtkTreePath* path,struct _GtkTreeIter* iter,void* data);
 * }
 */
public interface GtkTreeSelectionForeachFunc {

    void apply(java.lang.foreign.MemorySegment model, java.lang.foreign.MemorySegment path, java.lang.foreign.MemorySegment iter, java.lang.foreign.MemorySegment data);
    static MemorySegment allocate(GtkTreeSelectionForeachFunc fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$3199.const$3, fi, constants$42.const$1, scope);
    }
    static GtkTreeSelectionForeachFunc ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _model, java.lang.foreign.MemorySegment _path, java.lang.foreign.MemorySegment _iter, java.lang.foreign.MemorySegment _data) -> {
            try {
                constants$259.const$4.invokeExact(symbol, _model, _path, _iter, _data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


