// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkTreeStoreClass GtkTreeStoreClass
 * }
 */
public class GtkTreeStoreClass extends _GtkTreeStoreClass {

    GtkTreeStoreClass() {
        // Should not be called directly
    }
}

