// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkVPaned GtkVPaned
 * }
 */
public class GtkVPaned extends _GtkVPaned {

    GtkVPaned() {
        // Should not be called directly
    }
}

