// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet lang=c :
 * typedef struct _GtkWindow GtkWindow
 * }
 */
public class GtkWindow extends _GtkWindow {

    GtkWindow() {
        // Should not be called directly
    }
}

