// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GtkWidget GtkWidget;
 * }
 */
public final class GtkWidget extends _GtkWidget {

    // Suppresses default constructor, ensuring non-instantiability.
    private GtkWidget() {}
}


