// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _GUnixConnection GUnixConnection;
 * }
 */
public final class GUnixConnection extends _GUnixConnection {

    // Suppresses default constructor, ensuring non-instantiability.
    private GUnixConnection() {}
}


