// Generated by jextract

package org.purejava.appindicator;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
/**
 * {@snippet :
 * unsigned int (*hb_font_funcs_set_nominal_glyphs_func$func)(struct hb_font_t*,void*,unsigned int,unsigned int*,unsigned int,unsigned int*,unsigned int,void*);
 * }
 */
public interface hb_font_funcs_set_nominal_glyphs_func$func {

    int apply(java.lang.foreign.MemorySegment font, java.lang.foreign.MemorySegment font_data, int count, java.lang.foreign.MemorySegment first_unicode, int unicode_stride, java.lang.foreign.MemorySegment first_glyph, int glyph_stride, java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(hb_font_funcs_set_nominal_glyphs_func$func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1488.const$4, fi, constants$1482.const$1, scope);
    }
    static hb_font_funcs_set_nominal_glyphs_func$func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _font, java.lang.foreign.MemorySegment _font_data, int _count, java.lang.foreign.MemorySegment _first_unicode, int _unicode_stride, java.lang.foreign.MemorySegment _first_glyph, int _glyph_stride, java.lang.foreign.MemorySegment _user_data) -> {
            try {
                return (int)constants$1482.const$3.invokeExact(symbol, _font, _font_data, _count, _first_unicode, _unicode_stride, _first_glyph, _glyph_stride, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


