// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _PangoEngineShapeClass PangoEngineShapeClass;
 * }
 */
public final class PangoEngineShapeClass extends _PangoEngineShapeClass {

    // Suppresses default constructor, ensuring non-instantiability.
    private PangoEngineShapeClass() {}
}


