// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _PangoLanguage PangoLanguage;
 * }
 */
public final class PangoLanguage {

    // Suppresses default constructor, ensuring non-instantiability.
    private PangoLanguage() {}
}


