// Generated by jextract

package org.purejava.appindicator;

/**
 * {@snippet :
 * typedef struct _PangoAttrFontFeatures PangoAttrFontFeatures;
 * }
 */
public final class PangoAttrFontFeatures extends _PangoAttrFontFeatures {

    // Suppresses default constructor, ensuring non-instantiability.
    private PangoAttrFontFeatures() {}
}


