// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1577 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1577() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "pango_attr_list_unref",
        constants$13.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "pango_attr_list_copy",
        constants$5.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "pango_attr_list_insert",
        constants$13.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "pango_attr_list_insert_before",
        constants$13.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "pango_attr_list_change",
        constants$13.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "pango_attr_list_splice",
        constants$1043.const$2
    );
}


