// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1498 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1498() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "hb_font_set_user_data",
        constants$1423.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "hb_font_get_user_data",
        constants$5.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "hb_font_make_immutable",
        constants$13.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "hb_font_is_immutable",
        constants$10.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "hb_font_get_serial",
        constants$10.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "hb_font_changed",
        constants$13.const$1
    );
}


