// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3372 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3372() {}
    static final VarHandle const$0 = constants$3370.const$4.varHandle(MemoryLayout.PathElement.groupElement("_gtk_reserved4"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("widget"),
        JAVA_SHORT.withName("left_attach"),
        JAVA_SHORT.withName("right_attach"),
        JAVA_SHORT.withName("top_attach"),
        JAVA_SHORT.withName("bottom_attach"),
        JAVA_SHORT.withName("xpadding"),
        JAVA_SHORT.withName("ypadding"),
        MemoryLayout.paddingLayout(4)
    ).withName("_GtkTableChild");
    static final VarHandle const$2 = constants$3372.const$1.varHandle(MemoryLayout.PathElement.groupElement("widget"));
    static final VarHandle const$3 = constants$3372.const$1.varHandle(MemoryLayout.PathElement.groupElement("left_attach"));
    static final VarHandle const$4 = constants$3372.const$1.varHandle(MemoryLayout.PathElement.groupElement("right_attach"));
    static final VarHandle const$5 = constants$3372.const$1.varHandle(MemoryLayout.PathElement.groupElement("top_attach"));
}


