// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1069 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1069() {}
    static final VarHandle const$0 = constants$1065.const$1.varHandle(MemoryLayout.PathElement.groupElement("_g_reserved4"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(_GFileInputStreamClass._g_reserved5.class, "apply", constants$7.const$5);
    static final VarHandle const$2 = constants$1065.const$1.varHandle(MemoryLayout.PathElement.groupElement("_g_reserved5"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "g_file_input_stream_get_type",
        constants$3.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "g_file_input_stream_query_info",
        constants$39.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(g_file_input_stream_query_info_async$callback.class, "apply", constants$14.const$3);
}


