// Generated by jextract

package org.purejava.appindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1732 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1732() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cairo_surface_supports_mime_type",
        constants$9.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cairo_surface_get_font_options",
        constants$13.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cairo_surface_flush",
        constants$13.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "cairo_surface_mark_dirty",
        constants$13.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cairo_surface_mark_dirty_rectangle",
        constants$1643.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "cairo_surface_set_device_scale",
        constants$1531.const$0
    );
}


